version: '3'
services:
  djangoapp:
    # build: .
    image: site_blog
    command: sh run/run_web.sh
    volumes:
            #- .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/src/project/static # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/src/project/media  # <--  bind the media volume
    networks:
      - nginx_network
      - database1_network # <-- connect to bridge 
      - redis_network
      - elastic_network
    depends_on: # <-- wait for db to be 'ready' before starting the app
      - database1
      - elasticsearch
      - redis


  nginx:
    image: nginx
    ports:
      - 80:80
    # command: bash -c 'nginx -g "daemon off;"'
    volumes:
            #- ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/src/project/static # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/src/project/media   # <-- bind the media volume
    depends_on:
      - djangoapp
    networks:
      - nginx_network


  database1: # <-- IMPORTANT: same name as in DATABASE setting, otherwise Django won't find the database!  
    image: postgres
    env_file: # <-- we use the previously defined values
      - config/db/database1_env
    networks: # <-- connect to the bridge
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    command: redis-server --appendonly yes
    networks:
      - redis_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    # container_name: es01
    environment:
            #- node.name=es01
            # - discovery.seed_hosts=es02
            #- cluster.initial_master_nodes=es01,es02
            #- cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic_network
        
        
  
networks:
  nginx_network:
    driver: bridge
  database1_network: #<-- add the bridge
    driver: bridge
  redis_network:
    driver: bridge
  elastic_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume: # <-- declare the static volume
  media_volume: # <-- declare the media volume
  redis_volume:
  elastic_data:
